_macos_shared_job: &macos_shared_job
  language: shell
  before_install:
    - python --version
    - pip3 install -U pytest
    - pip3 install -U pylint
    - pip3 install -U codecov
  install:
    - pip3 install -r requirements.txt
  script: 
    - python3 setup.py install
    - pylint torchexpo/ tests/
    - pytest
  after_success: python3 -m codecov
language: python
dist: xenial
python:
  - 3.7
  - 3.8
matrix:
  include:
    - name: 'Python: 3.7 on macOS'
      os: osx
      osx_image: xcode10.2
      <<: *macos_shared_job
      after_success: 'python3 -m codecov'
    - name: 'Python: 3.8 on macOS'
      os: osx
      osx_image: xcode11.2
      <<: *macos_shared_job
before_install:
  - python --version
  - pip3 install -U pip
  - pip3 install -U pytest
  - pip3 install -U pylint
  - pip3 install codecov
install:
  - pip3 install -r requirements.txt
  - source ./scripts/conda/conda_install.sh
script:
  - python3 setup.py install
  - pylint torchexpo/ tests/
  - pytest
after_success:
  - codecov