language: python
dist: xenial
python:
  - 3.8
before_install:
  - 'python --version'
  - 'pip install -U pip'
  - 'pip install -U pylint'
  - 'pip install codecov'
install:
  - 'pip install -r requirements.txt'
script:
  - pylint torchexpo/ models/
after_success:
  - codecov