defaults: &defaults
  steps:
    - checkout
    - run:
        name: Install dependencies
        command: |
          sudo pip install -r requirements.txt
          sudo pip install pylint pytest
    - run:
        name: Building from Source
        command: sudo python setup.py install
    - run:
        name: Run Linter
        command: pylint torchexpo/ tests/
    - run:
        name: Run Tests
        command: pytest
        no_output_timeout: 60m
version: 2
jobs:
  linux_py36:
    docker:
      - image: circleci/python:3.6.4
    <<: *defaults
  linux_py37:
    docker:
      - image: circleci/python:3.7.9
    <<: *defaults
  linux_py38:
    docker:
      - image: circleci/python:3.8.5
    <<: *defaults
workflows:
  version: 2
  build_and_test:
    jobs:
      - linux_py36
      - linux_py37
      - linux_py38
    