defaults: &defaults
  steps:
    - checkout
    - run:
        name: Install dependencies
        command: |
          pip install -r requirements.txt
          pip install pylint pytest
    - run:
        name: Building from Source
        command: python setup.py install
    - run:
        name: Run Linter
        command: pylint torchexpo/ tests/
    - run:
        name: Run Tests
        command: python -m pytest -rA tests/
        no_output_timeout: 60m
version: 2
jobs:
  linux_py36:
    docker:
      - image: python:3.6
    <<: *defaults
  linux_py37:
    docker:
      - image: python:3.7
    <<: *defaults
  linux_py38:
    docker:
      - image: python:3.8
    <<: *defaults
workflows:
  version: 2
  build_and_test:
    jobs:
      - linux_py36
      - linux_py37
      - linux_py38
    