defaults: &defaults
  steps:
    - checkout
    - run:
        name: Install dependencies
        command: |
          pip install -r requirements.txt
          pip install pylint pytest
    - run:
        name: Building from Source
        command: python setup.py install
    - run:
        name: Run Linter
        command: pylint torchexpo/ tests/
    - run:
        name: Run Tests
        command: python -m pytest -rA tests/
        no_output_timeout: 60m
version: 2.1
jobs:
  linux_py36:
    docker:
      - image: python:3.6
    <<: *defaults
  linux_py37:
    docker:
      - image: python:3.7
    <<: *defaults
  linux_py38:
    docker:
      - image: python:3.8
    <<: *defaults
  android:
    docker:
      - image: circleci/android:api-30
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Download Assets & Make Android Ready
          command: |
            sudo chmod +x ./scripts/download_model_assets.sh
            ./scripts/download_model_assets.sh
      - run:
          name: Give Permissions
          command: |
            cd android && pwd
            sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: |
            cd android && pwd
            ./gradlew androidDependencies
      # - run:
      #     name: Build Debug APK
      #     command: |
      #       cd android && pwd
      #       ./gradlew :app:assembleDebug
      #       ./gradlew :app:assembleDebugAndroidTest
workflows:
  version: 2
  build_and_test:
    jobs:
      - linux_py36
      - linux_py37
      - linux_py38
      - android
    