from torchexpo.modules.torchexpo import TorchExpoModule
from torchexpo.modules.image_classification import ImageClassificationModule
from torchexpo.modules.image_segmentation import ImageSegmentationModule
from torchexpo.modules.sentiment_analysis import SentimentAnalysisModule